# Generated by Django 2.2.3 on 2019-07-29 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0002_auto_20190729_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compotencySelfReference', to='competency.Competency'),
        ),
    ]
