# Generated by Django 2.2.3 on 2019-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0003_auto_20190802_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='tags',
            field=models.ManyToManyField(blank=True, to='competency.Tag'),
        ),
    ]
