# Generated by Django 2.2.3 on 2019-07-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0004_auto_20190730_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competency.Subcategory'),
        ),
    ]
