# Generated by Django 2.2.3 on 2019-07-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0005_auto_20190730_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.Organization'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.Subcategory'),
        ),
    ]
