# Generated by Django 2.2.3 on 2019-08-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0008_project_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_directory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
