# Generated by Django 2.2.3 on 2019-08-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0009_project_file_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
