# Generated by Django 2.2.3 on 2019-08-29 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competency', '0011_cooperative'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='official',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='CooperativeEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('is_locked', models.BooleanField()),
                ('comment', models.TextField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.Cooperative')),
                ('enroller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_cooperativeenrollment_related_UserCreated', to=settings.AUTH_USER_MODEL)),
                ('user_last_modified', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_cooperativeenrollment_related_UserLastModified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
