# Generated by Django 2.2.4 on 2019-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0013_cooperativenews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativenews',
            name='date_published',
            field=models.DateField(),
        ),
    ]
