# Generated by Django 2.2.4 on 2019-09-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0014_auto_20190903_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativenews',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
