# Generated by Django 2.2.4 on 2019-09-05 11:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competency', '0016_cooperativechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('is_locked', models.BooleanField()),
                ('stage', models.IntegerField()),
                ('status', models.IntegerField()),
                ('is_pending', models.BooleanField()),
                ('date_proposed', models.DateField(default=datetime.date.today)),
                ('estimate_finish_date', models.DateField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.Cooperative')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competency.Project')),
                ('user_created', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_contract_related_UserCreated', to=settings.AUTH_USER_MODEL)),
                ('user_last_modified', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_contract_related_UserLastModified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
