# Generated by Django 2.2.3 on 2019-07-15 08:07

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=file.models.setPath),
        ),
    ]
