# Generated by Django 2.2.3 on 2019-08-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.TextField(),
        ),
    ]
