# Generated by Django 2.2.3 on 2019-08-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20190827_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.TextField(),
        ),
    ]
