# Generated by Django 2.2.4 on 2019-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190612_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_organization_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
