# Generated by Django 2.2.3 on 2019-08-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_active_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
