# Generated by Django 2.2.3 on 2019-08-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_active_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_type',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
