# Generated by Django 2.2.3 on 2019-08-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0009_project_file_directory'),
        ('user', '0005_auto_20190827_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='competencys',
            field=models.ManyToManyField(blank=True, to='competency.Competency'),
        ),
    ]
