# Generated by Django 2.2.3 on 2019-07-15 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PBModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('date_last_modified', models.DateField()),
                ('is_active', models.BooleanField()),
                ('is_locked', models.BooleanField()),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCreated', to=settings.AUTH_USER_MODEL)),
                ('user_last_modified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserLastModified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
