# Generated by Django 2.1.10 on 2019-07-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pbmodel',
            name='date_last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
