# Generated by Django 2.1.10 on 2019-07-16 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190716_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbmodel',
            name='user_created',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pbmodel',
            name='user_last_modified',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserLastModified', to=settings.AUTH_USER_MODEL),
        ),
    ]
