# Generated by Django 2.1.10 on 2019-07-17 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('is_locked', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_published', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCreated', to=settings.AUTH_USER_MODEL)),
                ('user_last_modified', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserLastModified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
