# Generated by Django 2.1.10 on 2019-07-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190715_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pbmodel_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PBModel'),
        ),
    ]
